# Generated by Django 5.2.6 on 2025-09-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
